server:
  port: 8082
spring:
  #  邮件配置
  mail:
    #    邮件服务器地址
    host: smtp.163.com
    #    协议
    protocol: smtp
    #    编码格式
    default-encoding: utf-8
    #    授权码（在邮箱开通服务时获取）
    password: OVYOTGBFUDYVQMBF
    #    发送者邮箱地址
    username: 15722851752@163.com
    #    端口（不同邮箱端口号不同）
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.188.100
    port: 5672
    listener:
      direct:
        #        开启手动确认
        acknowledge-mode: manual

  #redis配置
  redis:
    timeout: 10000ms
    #服务器端口
    host: 192.168.188.100
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #
    password: root
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5